version: '3.8'

services:
  web-terminal:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      - MAX_CONNECTIONS=${MAX_CONNECTIONS:-100}
      - SESSION_TIMEOUT=${SESSION_TIMEOUT:-3600}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./logs:/app/logs
      - ${HOME}:/workspace:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "http.get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - terminal-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/ssl/certs:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - web-terminal
    restart: unless-stopped
    networks:
      - terminal-network

networks:
  terminal-network:
    driver: bridge

volumes:
  nginx_logs:
  app_logs: